version: 2
updates:
  - package-ecosystem: npm
    directory: /TES-frontend
    schedule:
      interval: weekly
    groups:
      development:
        dependency-type: development
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /TES-frontend
    schedule:
      interval: weekly
